# Generated by Django 5.0.7 on 2024-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
