# Generated by Django 5.0.7 on 2024-07-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.author",
            ),
        ),
    ]
