# Generated by Django 5.0.7 on 2024-07-25 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_alter_revrat_options_revrat_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revrat",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
