# Generated by Django 5.0.7 on 2024-07-25 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_revrat_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="revrat",
            name="rating",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
