# Generated by Django 5.0.7 on 2024-07-25 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_revrat_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revrat",
            name="book",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="books.book"
            ),
        ),
    ]
